
name: Node CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - name: Add artifact to github
        uses: actions/upload-artifact@v2
        with:
          name: st-cp-dist.zip
          path: dist
#  test:
#    needs: build
#    strategy:
#      matrix:
#        os:
#          - macOS-latest
#          - ubuntu-latest
#          - windows-latest
#        node-version:
#          - 10.x
#          - 12.x
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: Install yarn
#        run: npm install -g yarn
#      - name: Download build
#        uses: actions/download-artifact@v2
#        with:
#          name: st-cp-dist.zip
#          path: dist
#      - name: Install dev dependencies
#        run: yarn
#      - name: Run tests
#        run: yarn test
#  cli-test:
#    needs: build
#    strategy:
#      matrix:
#        os:
#          - macOS-latest
#          - ubuntu-latest
#          - windows-latest
#        node-version:
#          - 10.x
#          - 12.x
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - name: Install yarn
#        run: npm install -g yarn
#      - name: Download build
#        uses: actions/download-artifact@v2
#        with:
#          name: st-cp-dist.zip
#          path: dist
#      - name: Install dev dependencies
#        run: yarn
#      - name: Run cli tests
#        run: yarn test:cli

  npm-publish:
    needs: [build]
    #needs: [test,cli-test]
    name: npm-publish
    runs-on: ubuntu-latest
    # only on master
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: st-cp-dist.zip
          path: dist
      - name: Install yarn
        run: npm install -g yarn
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Publish
        run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version